import { Button } from "std-widgets.slint";
export component SubmitterWindow inherits Window {
    width: 1024px;
    height: 512px;
    title: "Submitter";
    background: #242423;
    icon: @image-url("resources/icon.png");
    out property <color> second_color: #ccc5b9;
    out property <color> selection_background_color: #6c757d;
    out property <color> accent_color: #60d394;
    out property <string> primary_font: "Cascadia Code";
    in-out property <int> documents_inserted_counter;
    in-out property <int> links_inserted_counter;
    in-out property <int> tags_inserted_counter;
    
    callback document_title_accepted(string);
    callback document_author_accepted(string);
    callback document_origin_location_accepted(string);
    callback document_origin_date_accepted(string);
    callback document_links_accepted(string);
    callback document_tags_accepted(string);
    callback request_documents_len() -> int;
    callback request_links_len() -> int;
    callback request_tags_len() -> int;
    callback call_init_info();
    callback submit();

    function submit_formular() {
        title_input.text = "";
        author_input.text = "";
        location_input.text = "";
        link_input.text = "";
        tag_input.text = "";
        documents_inserted_counter = request_documents_len();
        links_inserted_counter = request_links_len();
        tags_inserted_counter = request_tags_len();
        submit();
    }
    function init_info() {
        documents_inserted_counter = request_documents_len();
        links_inserted_counter = request_links_len();
        tags_inserted_counter = request_tags_len();
    }

    HorizontalLayout {
        x: 0;
        y: 0;
        padding-top: 10px;
        padding-left: 10px;
        alignment: LayoutAlignment.start;
        HorizontalLayout {
            Text {
                font-size: 8px;
                font-family: root.primary_font;
                color: root.second_color;
                text: "Documents inserted: ";
            }
            Text {
                font-size: 8px;
                font-family: root.primary_font;
                color: root.accent_color;
                text: documents_inserted_counter;
            }
        }
        Text {
            font-size: 8px;
            font-family: root.primary_font;
            color: root.second_color;
            text: " | ";
        }
        HorizontalLayout {
            Text {
                font-size: 8px;
                font-family: root.primary_font;
                color: root.second_color;
                text: "Links inserted: ";
            }
            Text {
                font-size: 8px;
                font-family: root.primary_font;
                color: root.accent_color;
                text: links_inserted_counter;
            }
        }
        Text {
            font-size: 8px;
            font-family: root.primary_font;
            color: root.second_color;
            text: " | ";
        }
        HorizontalLayout {
            Text {
                font-size: 8px;
                font-family: root.primary_font;
                color: root.second_color;
                text: "Tags inserted: ";
            }
            Text {
                font-size: 8px;
                font-family: root.primary_font;
                color: root.accent_color;
                text: tags_inserted_counter;
            }
        }
    }

    VerticalLayout {
        width: root.width;
        height: root.height;
        alignment: LayoutAlignment.center;
        HorizontalLayout {
            alignment: LayoutAlignment.center;
            spacing: 30px;

            HorizontalLayout {
                height: 400px;
                spacing: 30px;
                HorizontalLayout {
                    Text {
                        font-family: primary_font;
                        font-size: 15px;
                        font-weight: 600;
                        height: 25px;
                        vertical-alignment: TextVerticalAlignment.center;
                        color: root.second_color;
                        text: "General";
                    }
                }
                dot0:=Rectangle {
                    background: root.second_color;
                    width: 1px;
                    Rectangle {
                        y: parent.y;
                        background: root.background;
                        border-radius: 30px;
                        border-color: root.second_color;
                        border-width: 1px;
                        width: 25px;
                        height: 25px;
                    }
                }
            }

            Rectangle {
                width: (root.width * 0.5);
                height: 400px;
                border-color: root.second_color;
                border-width: 1px;
                border-radius: 6px;
                VerticalLayout {
                    x: 20px;
                    width: parent.width;
                    height: parent.height;
                    alignment: LayoutAlignment.space-around;
                    HorizontalLayout {
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.second_color;
                            text: "Document Title";
                            font-family: primary_font;
                            font-size: 14px;
                            width: 150px;
                        }
                        init => {
                            title_input.focus();
                        }
                        Rectangle {
                            border-color: root.second_color;
                            border-width: 1px;
                            width: 300px;
                            height: 28px;
                            border-radius: 6px;
                            title_input:=TextInput {
                                horizontal-alignment: TextHorizontalAlignment.center;
                                vertical-alignment: TextVerticalAlignment.center;
                                color: root.second_color;
                                width: parent.width - 40px;
                                height: parent.height;
                                selection-background-color: root.selection_background_color;
                                accepted => {
                                    document_title_accepted(title_input.text);
                                    author_input.focus();
                                }
                            }
                        }

                    }
                    HorizontalLayout {
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.second_color;
                            text: "Author Title";
                            font-family: primary_font;
                            font-size: 14px;
                            width: 150px;
                        }
                        Rectangle {
                            border-color: root.second_color;
                            border-width: 1px;
                            width: 300px;
                            height: 28px;
                            border-radius: 6px;
                            author_input:=TextInput {
                                horizontal-alignment: TextHorizontalAlignment.center;
                                vertical-alignment: TextVerticalAlignment.center;
                                color: root.second_color;
                                width: parent.width - 40px;
                                height: parent.height;
                                selection-background-color: root.selection_background_color;
                                accepted => {
                                    document_author_accepted(author_input.text);
                                    location_input.focus();
                                }
                            }
                        }
                    }
                    HorizontalLayout {
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.second_color;
                            text: "Origin location";
                            font-family: primary_font;
                            font-size: 14px;
                            width: 150px;
                        }
                        Rectangle {
                            border-color: root.second_color;
                            border-width: 1px;
                            width: 300px;
                            height: 28px;
                            border-radius: 6px;
                            location_input:=TextInput {
                                horizontal-alignment: TextHorizontalAlignment.center;
                                vertical-alignment: TextVerticalAlignment.center;
                                color: root.second_color;
                                width: parent.width - 40px;
                                height: parent.height;
                                selection-background-color: root.selection_background_color;
                                accepted => {
                                    document_origin_location_accepted(location_input.text);
                                    window_popup.show();
                                }
                            }
                        }
                    }
                    HorizontalLayout {
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.second_color;
                            text: "Origin Date";
                            font-family: primary_font;
                            font-size: 14px;
                            width: 150px;
                        }
                        Rectangle {
                            window_popup:= PopupWindow {
                                close-policy: PopupClosePolicy.close-on-click-outside;
                                Rectangle {
                                    y: parent.y + 80px;
                                    background: root.background;
                                    width: 300px;
                                    height:  100px;
                                    border-width: 1px;
                                    border-color: root.second_color;
                                    border-radius: 6px;
                                    VerticalLayout {
                                        alignment: LayoutAlignment.center;
                                        height: parent.height;
                                        HorizontalLayout {
                                            width: parent.width;
                                            alignment: LayoutAlignment.center;
                                            spacing: 20px;
                                            Text {
                                                vertical-alignment: TextVerticalAlignment.center;
                                                color: root.second_color;
                                                text: "Datum";
                                                font-family: primary_font;
                                                font-size: 14px;
                                                width: 50px;
                                            }
                                            Rectangle {
                                                border-color: root.second_color;
                                                border-width: 1px;
                                                width: 120px;
                                                height: 28px;
                                                border-radius: 6px;
                                                calender_input:=TextInput {
                                                   horizontal-alignment: TextHorizontalAlignment.center;
                                                    vertical-alignment: TextVerticalAlignment.center;
                                                    color: root.second_color;
                                                    width: parent.width - 7px;
                                                    height: parent.height;
                                                    selection-background-color: root.selection_background_color;
                                                    accepted => {
                                                        document_origin_date_accepted(calender_input.text);
                                                        window_popup.close();
                                                        link_input.focus();
                                                    }
                                                }
                                                init => {
                                                    calender_input.focus();
                                                }
                                                TouchArea {
                                                    width: 100%;
                                                    height: 100%;
                                                    clicked => {
                                                        calender_input.focus();
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            border-color: root.second_color;
                            border-width: 1px;
                            width: 150px;
                            height: 28px;
                            border-radius: 6px;
                            Image {
                                source: @image-url("resources/clock.png");
                                width: 15px;
                                height: 15px;
                            }
                            TouchArea {
                                clicked => {
                                    window_popup.show();
                                }
                            }
                        }
                    }
                    HorizontalLayout {
                        links_text:= Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.second_color;
                            text: "Document Links";
                            font-family: primary_font;
                            font-size: 14px;
                            width: 150px;
                        }
                        Rectangle {
                            border-color: root.second_color;
                            border-width: 1px;
                            width: 300px;
                            height: 28px;
                            border-radius: 6px;
                            link_input:=TextInput {
                                horizontal-alignment: TextHorizontalAlignment.center;
                                vertical-alignment: TextVerticalAlignment.center;
                                color: root.second_color;
                                width: parent.width - 40px;
                                height: parent.height;
                                selection-background-color: root.selection_background_color;
                                accepted => {
                                    document_links_accepted(link_input.text);
                                    tag_input.focus();
                                }
                            }
                        }

                    }
                    HorizontalLayout {
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.second_color;
                            text: "Document Tags";
                            font-family: primary_font;
                            font-size: 14px;
                            width: 150px;
                        }
                        Rectangle {
                            border-color: root.second_color;
                            border-width: 1px;
                            width: 300px;
                            height: 28px;
                            border-radius: 6px;
                            tag_input:=TextInput {
                                horizontal-alignment: TextHorizontalAlignment.center;
                                vertical-alignment: TextVerticalAlignment.center;
                                color: root.second_color;
                                width: parent.width - 40px;
                                height: parent.height;
                                selection-background-color: root.selection_background_color;
                                accepted => {
                                    document_tags_accepted(tag_input.text);
                                    info_text.text = title_input.text;
                                    info_text.width = title_input.text.character-count * 8px;
                                    info.visible = true;
                                    submit_formular();
                                }
                            }
                        }
                    }
                    info:= HorizontalLayout {
                    visible: true;
                    spacing: 0px;
                        Text {

                            font-size: 8px;
                            color: root.second_color;
                            font-family: root.primary_font;
                            width: 8px * 9;
                            text: "Dokument ";
                        }
                        info_text:=Text {
                            font-size: 8px;
                            color: root.accent_color;
                            font-family: root.primary_font;
                            width: 0px;
                        }
                        Text {
                            width: 8px * 40;
                            font-size: 8px;
                            color: root.second_color;
                            font-family: root.primary_font;
                            text: " wurde manuell eingereicht und registriert.";
                        }
                    }
                }
            }
        }
    }
}