global DashboardTheme {
    out property <brush> background : #141414;
    out property <brush> background_widget : #26252A;

    out property <color> color_blue : #2573CC;
    out property <color> color_green : #32AB4F;
    out property <color> color_yellow : #CBA215;
    out property <color> color_purple : #5E3A9F;

    out property <color> text_color : #CCCCCC;
    out property <color> text_emphasize <=> color_blue;
    out property <color> icon_color <=> text_color;

    out property <image> image_rect : @image-url("../resources/rect.png");
    out property <image> image_icon : @image-url("../resources/icon.png");
    out property <image> image_download : @image-url("../resources/download.png");
    out property <image> image_folder : @image-url("../resources/folder.png");
    out property <image> image_menu : @image-url("../resources/menu.png");
    out property <image> image_pdf : @image-url("../resources/pdf.png");
    out property <image> image_profile : @image-url("../resources/profile.png");
    out property <image> image_submit : @image-url("../resources/submit.png");
    out property <image> image_tag : @image-url("../resources/tag.png");
    out property <image> image_versions : @image-url("../resources/versions.png");
    out property <image> image_search : @image-url("../resources/search.png");

    out property <length> default_icon_size : 25px;
    out property <length> big_icon_size : 100px;
    out property <length> default_gap_small : 7px;
    out property <length> default_gap_medium : 20px;
    out property <length> default_gap_large : 55px;

    out property <length> default_text_input_h : 53px;
    out property <length> default_text_input_w : 500px;

    out property <length> corner_radius : 12px;
    out property <length> padding <=> default_gap_small;

    out property <length> default_font_size : 24px;
    out property <length> mdeium_font_size : 25px;
}

component FolderTab inherits Rectangle {
    in property <brush>  fcolor: DashboardTheme.background_widget;
    in property <length> radius       : 12px;
    in-out property <string> content;
    width: t.width + DashboardTheme.default_gap_medium;
    border-radius: radius;
    background: fcolor;
    height: 40px;
    Image {
        width: DashboardTheme.default_icon_size;
        height: DashboardTheme.default_icon_size;
        x: (parent.width - self.width) / 2;
        y: -(self.height / 2) + 8px;
        source: DashboardTheme.image_rect;
        colorize: fcolor;
        z: 0;
    }
    t:=Text {
        color: DashboardTheme.text_color;
        text <=> content;
    }
}

component ClientDashboardIconField {
    in property <bool> round : false;
    in property <bool> descriptor : false;
    in property <bool> border : false;
    in property <string> descriptor_text;
    in property <image> image;
    in property <bool> tooltip : false;
    in property <bool> colorize;
    in property <brush> background : Colors.transparent;
    in-out property <string> tooltip_text;
    Rectangle {
        clip: false;
        border-radius: root.round ? 800px : DashboardTheme.corner_radius;
        border-width: root.border ? 1px : 0;
        border-color: DashboardTheme.background_widget;
        horizontal-stretch: 0;
        max-width: DashboardTheme.default_icon_size + (descriptor ? DashboardTheme.default_gap_medium : DashboardTheme.default_gap_small);
        background: root.background;

        a:=TouchArea {
            width: 100%;
            height: 100%;
            tooltip_popup:= FolderTab {
                visible: false;
                y: 60px;
                z: 1;
                content <=> tooltip_text;
            }
            property <bool> tw : false;
            changed has-hover => {
                if (root.tooltip) {
                    if (self.has-hover) {
                        if (!tw) {
                            tooltip_popup.visible = true;
                            tw = !tw;
                        }
                    } else {
                        if (tw) {
                            tooltip_popup.visible = false;
                            tw = !tw;
                        }
                    }
                }
            }
        }
        VerticalLayout {
            spacing: 9px;
            padding: descriptor ? DashboardTheme.default_gap_medium : DashboardTheme.default_gap_small;
            HorizontalLayout {
                alignment: LayoutAlignment.center;
                Image {
                    width: DashboardTheme.default_icon_size;
                    height: DashboardTheme.default_icon_size;
                    image-rendering: ImageRendering.smooth;
                    source: root.image;
                    states [
                        hovered when a.has-hover && root.colorize : {
                            colorize: DashboardTheme.color_blue;
                        }
                    ]

                }
            }
            if descriptor: Text {
                horizontal-alignment: TextHorizontalAlignment.center;
                vertical-alignment: TextVerticalAlignment.center;
                text: descriptor_text;
                color: DashboardTheme.text_emphasize;
            }
        }
    }
}

component ClientDashboardContainer {
    Rectangle {
        background: DashboardTheme.background_widget;
        border-radius: DashboardTheme.corner_radius;
        @children
    }
}

component ClientDashboardSection {
    in property <bool> top_line : false;
    in property <bool> bottom_line : false;
    in property <length> spacing : 0;
    VerticalLayout {
        spacing: root.spacing;
        if top_line : Rectangle {
            height: 1px;
            width: 100%;
            background: DashboardTheme.background_widget;
        }
        @children
        if bottom_line : Rectangle {
            height: 1px;
            width: 100%;
            background: DashboardTheme.background_widget;
        }
    }
}

component ClientDashboardMenu inherits ClientDashboardSection {
    bottom_line: true;
    top_line: true;
    spacing: 10px;
    HorizontalLayout {
        spacing: DashboardTheme.default_gap_large;
        alignment: LayoutAlignment.space-around;
        HorizontalLayout {
            horizontal-stretch: 0;
            spacing: DashboardTheme.default_gap_small;
            ClientDashboardIconField {
                horizontal-stretch: 0;
                image: DashboardTheme.image_menu;
                border: true;
                tooltip: true;
                tooltip_text: "Menu";
                colorize: true;
            }
            ClientDashboardIconField {
                horizontal-stretch: 0;
                image: DashboardTheme.image_profile;
                border: true;
                tooltip: true;
                tooltip_text: "Profile";
                colorize: true;
            }
            ClientDashboardIconField {
                horizontal-stretch: 0;
                image: DashboardTheme.image_download;
                border: true;
                tooltip: true;
                tooltip_text: "Download Software";
                colorize: true;
            }
        }
        HorizontalLayout {
            spacing: DashboardTheme.default_gap_small;
            VerticalLayout {
                horizontal-stretch: 1;
                alignment: LayoutAlignment.center;
                Rectangle {
                    clip: true;
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        HorizontalLayout {
                            padding-left: 10px;
                            padding-right: 10px;
                            alignment: LayoutAlignment.start;
                            Image {
                                image-rendering: ImageRendering.smooth;
                                width: DashboardTheme.default_icon_size - 6px;
                                height: DashboardTheme.default_icon_size - 6px;
                                source: DashboardTheme.image_search;
                            }
                            HorizontalLayout {
                                horizontal-stretch: 1;
                                width: 90%;
                                alignment: LayoutAlignment.center;
                                Text {
                                    horizontal-alignment: TextHorizontalAlignment.center;
                                    vertical-alignment: TextVerticalAlignment.center;
                                    text: "Suchen oder filtern";
                                    font-weight: 700;
                                    color: DashboardTheme.text_color;
                                }
                            }
                        }
                    }
                    border-radius: DashboardTheme.corner_radius / 2;
                    max-width: DashboardTheme.default_text_input_w * 2;
                    horizontal-stretch: 1;
                    height: DashboardTheme.default_icon_size + 5px;
                    preferred-width: DashboardTheme.default_text_input_w;
                    background: DashboardTheme.background_widget;
                }
            }
        }
        HorizontalLayout {
            horizontal-stretch: 0;
            spacing: -15px;
            ClientDashboardIconField {
                image: DashboardTheme.image_versions;
                background: DashboardTheme.color_green;
                round: true;
                tooltip: true;
                tooltip_text: "Versionen";
                width: DashboardTheme.default_icon_size + 12px;
                height: DashboardTheme.default_icon_size + 12px;
            }
            ClientDashboardIconField {
                image: DashboardTheme.image_tag;
                background: DashboardTheme.color_blue;
                round: true;
                tooltip: true;
                tooltip_text: "Schlagwörter";
                width: DashboardTheme.default_icon_size + 12px;
                height: DashboardTheme.default_icon_size + 12px;
            }
            ClientDashboardIconField {
                image: DashboardTheme.image_folder;
                background: DashboardTheme.color_purple;
                round: true;
                tooltip: true;
                tooltip_text: "Verbindungen";
                width: DashboardTheme.default_icon_size + 12px;
                height: DashboardTheme.default_icon_size + 12px;
            }
            ClientDashboardIconField {
                image: DashboardTheme.image_submit;
                background: DashboardTheme.color_yellow;
                round: true;
                tooltip: true;
                tooltip_text: "Einstellen";
                width: DashboardTheme.default_icon_size + 12px;
                height: DashboardTheme.default_icon_size + 12px;
            }
        }
    }
}

export component ClientDashboard inherits Window {
    default-font-family: "SF Mono";
    Flickable {
        Rectangle {
        background: DashboardTheme.background;
        width: 100%;
        height: 100%;
        /* content */
            VerticalLayout {
                /* menu bar */
                ClientDashboardMenu {

                }

            }
        }

    }
}